### ISSUE TITLE
Season 2 - Episode 28: Cloud Computing Services

### ISSUE THREAD

**Issue by Hameds** [softwaretalks/softwaretalks#43]
<div dir="rtl">
موضوعات پیشنهادی برای برنامه سه‌شنبه ۲۱ آبان ۹۸:

- تعریف و تاریخچه کوتاه پردازش ابری
- معرفی کوتاه شرکت‌های اصلی ارائه‌کننده خدمات (در ایران و خارج از ایران)
- معرفی انواع خدمات پردازش ابری از جمله IaaS و PaaS و FaaS
- منابع یادگیری درباره سرویس‌های پردازش ابری
- چالش‌های مرتبط با سرویس‌های پردازش ابری (با نگاه به چالش‌های مختص ایران) 
- موقعیت‌های شغلی و بازار کار در حوزه سرویس‌های پردازش ابری

**توجه** شما هم اگر پیشنهادی برای سرفصل‌های این برنامه دارید می‌توانید در همین issue نظر بدهید.

همچنین منابع معرفی شده در این اپیزود هم در این issue قرار خواهند گرفت
</div>

**Comment by hbahadorzadeh** [comment]
لینک دوره آموزشی OpenStack
https://www.oreilly.com/library/view/openstack-certification-2e/9780134836959/
